lib/igniter/project/igniter_config.ex

Having a fully-qualified URL lets you cmd+click and go there from your editor! (on macOS - its probably ctrl+click on Windows)

docs: Add protocol to config doc link to make it usable

---

lib/igniter/util/install.ex

This PR changes the title of the result of running all installers to only include the installers that actually ran. It also only runs the installers if there is at least one task that has an installer.

improvement: only show executed installers

---

lib/igniter.ex

This PR adds the support for "notices", which is the programmable output that will be printed once an Igniter runs successfully. They are printed in green, and are intended for things like "next steps" and such.
UPD: this PR also pretties up the output by surrounding relevant warning and notice sections with blank lines where necessary. The old "Notices" has also been renamed to "Warnings".

improvement: support "notices"

---

lib/igniter/code/common.ex
lib/igniter/code/keyword.ex
lib/igniter/code/map.ex
lib/igniter/project/deps.ex

Fix move to single child block

---

lib/igniter/code/common.ex
test/igniter/project/config_test.exs

Reverts ash-project/igniter#70

Revert "fix: escape injected code in Common.replace_code/2"

---

lib/igniter.ex
test/igniter/code/file_test.exs

to start a discussion about how best to add support for patching non-elixir files

support for non-elixir files with create_new_file, update_file, include_existing_file, include_or_create_file, create_or_update_file

---

test/igniter/project/config_test.exs

Adding two failing tests for the `Config.configure/6` function. The first has to do with nesting (seems like there's still a bug lurking around). The second one has to do with injecting quoted code.
Currently, the first test fails with:
```
error: syntax error before: '=>'
│
2 │ config :level1, :level2, level3: ["hello1" => "world1"]
```
and the second fails with no matching function clause error.

improvement: add failing config tests

---

lib/igniter/code/module.ex
test/igniter/code/module_test.exs

Module.find_all_matching_modules only consider Elixir Files

---

test/igniter/code/common_test.exs

As discussed, here is a failing test for replacing code with multiple lines. Thanks for taking a look!

Add failing test for multiline replacements

---

lib/igniter/libs/ecto.ex
test/igniter/libs/ecto_test.exs

Fix a typo and _try_ to add a test although I'm not sure that test is correctly handling `igniter.assigns[:test_files]`.

Fix gen_migration :overwrite

---

lib/mix/task.ex

fix: make task run/1 overridable

---

installer/README.md

docs: update installer build instructions

---

lib/igniter/project/deps.ex

Add an example for Igniter.Project.Deps.app_dep/2

---

lib/igniter/code/common.ex
lib/igniter/project/application.ex
test/igniter/code/common_test.exs
test/igniter/project/application_test.exs

Ignitier.Project.Application.app_module/1 returning tuple

---

test/igniter/code/common_test.exs

Add a test for rightmost

---

mix.exs

docs: add module grouping to generated docs

---

lib/igniter/libs/phoenix.ex

chore: Fix typo "pipline" -> "pipeline"

---

lib/igniter.ex
lib/igniter/code/common.ex
lib/igniter/code/function.ex
lib/igniter/code/keyword.ex
lib/igniter/project/application.ex
lib/igniter/project/mix_project.ex
test/igniter/project/mix_project_test.exs

Introduces the `Igniter.Project.MixProject.update/4` function proposed in #162.

improvement: `Igniter.Project.MixProject.update/4`

---

installer/lib/private/deps_compile.ex

The two deprecations are:
1. `Mix.Rebar.local_rebar_cmd/1 -> Mix.Rebar.local_rebar_path/1`
2. `Mix.Rebar.rebar_cmd/1 -> Mix.Rebar.available?/1 + Mix.Rebar.rebar_args/2`
I haven't checked whether all of this is covered by existing tests and am not entirely sure how to test this properly. Suggestions welcome.

fix: handle mix rebar deprecations for 1.18

---

test/igniter/project/config_test.exs

Not much but I was using that function and was not sure if it was working as I expected, so I wrote these tests to double check.

Add tests for `Config.modify_configuration_code/5`

---

lib/igniter/libs/phoenix.ex
test/igniter/libs/phoenix_test.exs
test/igniter/project/module_test.exs

fix: `web_module/1` duplicating Web suffix

---

lib/igniter/project/config.ex
test/igniter/project/config_test.exs

Change default updater fn for configure_runtime_env/6 to match configure/6

---

lib/igniter/test.ex

feat: add phx_test_project

---

lib/mix/tasks/igniter.refactor.rename_function.ex

* [`lib/mix/tasks/igniter.refactor.rename_function.ex`](diffhunk://#diff-49e5a897ce2c46999601849963d782700b23cf7eb40b7f1dfe8595dd7163b6abL6-R6): Updated the `@shortdoc` to "Rename functions across a project with automatic reference updates."

Add `shortdoc` to `igniter.refactor.rename_function.ex`

---

lib/mix/tasks/igniter.add.ex
test/mix/tasks/igniter.add_test.exs

feat: add igniter.add task

---

lib/igniter/code/common.ex

docs: add spec for within

---

lib/igniter/code/common.ex

Just adding a documentation fix. The output is quite a bit different too, so I'm just showing what outputs.

Adds doc fixes for Code.Common.move_to_cursor

---

lib/mix/tasks/igniter.gen.task.ex
test/mix/tasks/igniter.gen.task_test.exs

Add impl to generated mix task

---

lib/mix/tasks/igniter.gen.task.ex
test/mix/tasks/igniter.gen.task_test.exs

Remove controversial opinion: bash

---

installer/lib/mix/tasks/igniter.install.ex

Add missing --only flag documentation for installer install task

---

.github/workflows/elixir.yml
installer/mix.exs
lib/igniter/project/deps.ex
mix.exs

Leave anything that you believe does not apply unchecked.

Use hex to support looking up org package versions

---

lib/igniter.ex

Leave anything that you believe does not apply unchecked.

docs: Update argument error message
