ash-project/igniter

- lib/code/common.ex
- lib/code/list.ex
- lib/igniter.ex
This is a minor PR aimed at slightly improving the readability of the code. In addition to the actual changes, I would like to propose the following (happy to implement myself, but wanted to discuss before jumping to writing code, esp since it might lead to deprecating previous names):
1. `Igniter.Code.Common.env_at_cursor/1` doesn't yet have a cursor (it gets inserted as the first step). Perhaps a more descriptive name would be `(get_)current_environment/1`?
2. The name for `Igniter.Code.Common.add_code/3` doesn't immediately indicate where the code is added. How's `insert_code/3` to explicitly indicate that it gets inserted exactly where the zipper is focused?
3. The name `Igniter.Code.Common.highest_adjacent_block/1` was a bit confusing to me (perhaps because the code nests …
> Miscellaneous clarifications and cleaning up

- documentation/writing-generators.md
- mix.exs
Nice library! :D
I noticed a small error in the writing generators guide. When calling `create_new_elixir_file`, the `igniter` argument was specified twice.
Also adding `source_url` to `mix.exs` so that all functions have code links in HexDocs.
> Fix "Writing generators" code example + add source_url to enable link to code on HexDocs

- lib/code/module.ex
- test/code/module_test.exs
Adds `Igniter.Code.Module.proper_test_location/1` in order to be able to output test file paths, i.e. `MyApp.HelloTest` -> `test/my_app/hello_test.exs`.
Note: I'm not sure if it's a common scenario to have the test file _not_ end with `Test` in the module name, but I wanted to account for it just in case.
> improvement: add proper_test_location/1

- lib/code/module.ex
- test/code/module_test.exs
This PR adds `proper_test_support_location/1`, which returns idiomatic test support location such as `MyApp.DataCase` -> `test/support/data_case.ex`. It also inlines the tests as doctests for readability.
> improvement: add proper_test_support_location/1

- lib/util/install.ex
This PR fixes how the dependency version string is parsed in `igniter.install`. Right now, adding a `ref` with another `@` at the end raises a match error because the first split produces three parts instead of two, making lines 201 and 214 are not reachable.
> fix: version string splitting

- lib/igniter.ex
- lib/igniter/util/install.ex
This PR implements https://github.com/ash-project/igniter/issues/24 and refactors `Igniter.Util.Install` to use it. It also adds `Igniter.has_changes?/1` and changes one place where it's relevant. The logic in the installer is now as follows: if there are changes when running `Igniter.apply_and_fetch_dependencies/1`, prompt the user to accept them and install dependencies. If not, do nothing and move on. 
Open question: do we still need the `options` variable in the installer, considering the changes? (I marked it with `# TODO` in the code for now.) Marking as draft for now.
> improvement: add Igniter.apply_and_fetch_dependencies/1 and Igniter.has_changes?/1

- lib/igniter/code/list.ex
There's currently a minor inconsistency between `Igniter.Code.List.append_new_to_list/2` and `Igniter.Code.List.prepend_new_to_list/2`, namely, `append_new_to_list/2` sometimes returns `zipper` and sometimes `{:ok, zipper}`. This PR is a minor fix to ensure `{:ok, zipper}` is always returned.
> fix: always return {:ok, zipper} in append_new_to_list/2

- lib/igniter.ex
There's a bug in `Igniter.apply_and_fetch_dependencies/2`, which is that changes are previewed only for `mix.exs` but run on _all_ files. This PR adds a path for `mix.exs` to the actual Igniter invocation.
> fix: include only "mix.exs" in the actual run in apply_and_fetch_dependencies

- lib/igniter/util/install.ex
Depending on the order in which Mix loads tasks, the original installer ordering may be lost. For example, `mix igniter.install ash_postgres@path:../ash_postgres,ash_money@path:../ash_money` installs AshMoney before AshPostgres. This PR adds a sorting step to return the original ordering passed as arguments to `igniter.install`.
> fix: preserve original ordering in Util.Install

- lib/igniter/project/deps.ex
This is a minor improvement to append dependencies to `mix.exs` instead of prepending. This change is not critical but is helpful for ordering purposes, in light of https://github.com/ash-project/igniter/pull/33.
> improvement: append dependency to mix instead of prepending

- lib/igniter/project/config.ex
There's a tiny subtle bug when ensuring default configs exist, which is that `file_name` (i.e. `dev.exs`) is passed into `ensure_default_configs_exist` which has guards on file paths instead, i.e. `config/dev.exs`, so it never gets invoked. This PR fixes it by passing the full `file_path` instead.
> fix: pass file_path to `ensure_default_configs_exist`

- lib/igniter/code/module.ex
Sometimes it is necessary to create a new module of a certain kind, i.e. a test or a test support, for which we have helpers to get their idiomatic location. This PR slightly refactors `find_and_update_or_create_module/5` in a backwards-compatible way to support an optional `:kind` flag, which defaults to `:lib`, but also supports `:test` and `:test_support`.
> improvement: support :kind in find_and_update_or_create_module/5

- README.md
Igniter needs to be installed for all environments!
> docs: Remove `only: [:dev]` in setup instructions

- .tool-versions
- lib/igniter/code/common.ex
- lib/igniter/code/function.ex
- lib/igniter/code/keyword.ex
- lib/igniter/code/map.ex
- lib/igniter/code/module.ex
- lib/igniter/code/tuple.ex
- lib/igniter/project/deps.ex
- lib/igniter/util/debug.ex
I love just browsing and reading code, and while doing so with `Igniter`, noticed some zipper usage that couple be simplified.
Commits are atomic and can be reviewed independently. Happy to omit anything you don't want; just let me know. 🙂
> refactor: simplify zipper usage

- lib/igniter/code/module.ex
Seems like we forgot to remove `:kind` from the documentation for `find_and_update_or_create_module/5` when we went with the `:path` option only.
> chore: remove :kind from docs

- lib/igniter/util/info.ex
- lib/igniter/util/install.ex
This PR refactors `Igniter.Util.Install.install/3` into three different function clauses where `deps` can be either a string (separated with a comma), a list of strings, or a list of source dependencies (i.e. `{:ash, "~> 3.0"}`). This makes it possible to run `igniter.install` from a non-CLI context. This PR also adds a fourth `opts` function argument to `Igniter.Util.Install.install/3` (now `install/4`) and propagates it to `Igniter.Util.Info`. Note: I also removed `Application.ensure_all_started(:req)` since `Req` is not used anymore it seems.
> improvement: support tuple dependencies in igniter.install

- lib/igniter/code/function.ex
- test/igniter/code/function_test.exs
This PR adds `Igniter.Code.Function.argument_equals?/3` to make it easy to check argument equality. It also adds a note to `Function.argument_matches_pattern?/3` to clarify that equality checks should be done with `argument_equals?/3`.
> improvement: add Function.argument_equals?/3

- lib/igniter.ex
Adding the `config` directory to `include_all_elixir_files/1` since Igniter works with configs frequently.
> improvement: include config in include_all_elixir_files

- lib/igniter/code/function.ex
- lib/igniter/project/config.ex
- test/igniter/project/config_test.exs
This PR splits (and deprecates) `Igniter.Project.Config.configures?/3` into `Igniter.Project.Config.configures_key/4` and `Igniter.Project.Config.configures_root_key/3` to allow passing just the root key, atom keys, and list keys (as keyword paths).
Additionally, it addresses some of the issues discussed in #51, specifically, it:
- moves `Igniter.Code.Keyword.keyword_has_path?/2` inside the matching function in `Igniter.Code.Function.move_to_function_call_in_current_scope/4` to make sure deeply nested keys defined in a _later_ (that is, not first) run of the same root key configuration is checked. Previously, it was matching on the root key and checking it within a `case`, so there was a possibility it would match on the first occurrence, fail to find a nested key, and return `false` …
> fix: configures?/3 -> configures_key & configures_root_key

- lib/igniter/code/keyword.ex
- lib/igniter/project/config.ex
This PR makes sure that `Keyword.remove_keyword_key/2` always returns `:error` when it fails. It also modifies `try_update_three_arg/5` and `try_update_two_arg/5` to use `argument_equals?` for keys instead of `argument_matches_pattern?`.
> fix: :error consistency in remove_keyword_key and argument_equals? in Config.configure

- lib/igniter/code/common.ex
- test/igniter/project/config_test.exs
In `Common.replace_code/2`, the code should be escaped before being injected. For example, when updating an existing config value to a list of string tuples, `Common.replace_code/2` will just inject it resulting in:
```elixir
[{"hello", "world"}]
```
instead of
```elixir
{:__block__,
[
trailing_comments: [],
leading_comments: [],
closing: [line: 1, column: 20],
line: 1,
column: 1
],
[
[
{:__block__,
[
trailing_comments: [],
leading_comments: [],
closing: [line: 1, column: 19],
line: 1,
column: 2
],
[
{{:__block__,
[
trailing_comments: [],
leading_comments: [],
delimiter: "\"",
line: 1,
column: 3
], ["hello"]},
{:__block__,
[
trailing_comments: [],
leading_comments: [],
delimiter: "\"",
line: 1,
column: 12
], ["world"]}}
]}
]
]}
```
and Sourceror then fails to put it back into string form …
> fix: escape injected code in Common.replace_code/2

- test/igniter/project/config_test.exs
It seems that are few more bugs lurking in the `configure/6` function (probably in the functions that it uses underneath). I can't quite get a hang on what's wrong and can't look into it further at the moment but just wanted to flag these.
Current behavior for the first test (config set to []) is:
```elixir
import Config
config :foo,
SomeModule,
(
[]
{:level1, [level2: :value]}
)
```
and for the second is:
```
* (SyntaxError) invalid syntax found on nofile:3:43:
error: syntax error before: '=>'
│
3 │ config :foo, SomeModule, level1: [:level2 => [level3: :value]]
│                                           ^
│
└─ nofile:3:43
```
> WIP: fix Config.configure/6

- README.md
- documentation/writing-generators.md
Changed "eachother" to "each other" in README.md and the "Writing Generators" documentation.
> docs: fix spelling in the README and writing generators documentation

- lib/igniter/code/common.ex
- lib/igniter/code/function.ex
- lib/igniter/code/list.ex
- lib/igniter/code/tuple.ex
- lib/mix/tasks/igniter.upgrade_igniter.ex
- test/igniter/code/common_test.exs
This PR implements #112, if accepted.
Note: If #111 is merged first, this PR should be rebased to replace a [private function](https://github.com/ash-project/igniter/pull/111/files#diff-7a0262dc445950a410b05838f4415a4532f854ceebf504cacd6b9c0280000ad6R92-R94) used there with a call to `Igniter.Code.Common.move_upwards(zipper, 4)`. If this PR is merged first, #111 can be rebased instead.
> `Igniter.Code.Common`: Support integer argument in `move_right/2` and `move_upwards/2` and add `move_left/2`

- lib/igniter/code/common.ex
- lib/igniter/project/application.ex
- test/igniter/code/common_test.exs
- test/igniter/project/application_test.exs
This PR also fixes two bugs in `Common.expand_literal/1`. Previously, the following would be returned:
```elixir
iex(1)> ":foo" |> Sourceror.parse_string!() |> Sourceror.Zipper.zip() |> Igniter.Code.Common.expand_literal()
{:ok, {:__block__, [trailing_comments: [], leading_comments: [], line: 1, column: 1], [:foo]}}
iex(2)> "@foo" |> Sourceror.parse_string!() |> Sourceror.Zipper.zip() |> Igniter.Code.Common.expand_literal()
{:ok,
{:@, [trailing_comments: [], leading_comments: [], line: 1, column: 1],
[{:foo, [trailing_comments: [], leading_comments: [], line: 1, column: 2], nil}]}}
```
With this PR:
```elixir
iex(1)> ":foo" |> Sourceror.parse_string!() |> Sourceror.Zipper.zip() |> Igniter.Code.Common.expand_literal()
{:ok, :foo}
iex(2)> "@foo" |> Sourceror.parse_string!() |> …
```
> improvement: resolve project app names set using a module attribute

- lib/igniter/test.ex
I found myself writing [some tests](https://github.com/zachallaun/mneme/blob/main/test/mix/tasks/mneme.install_test.exs) where I wanted the diff as a string, but couldn't use `capture_io` and `Igniter.Test.puts_diff/2` because it included terminal escape codes for color.
This PR adds `Igniter.Test.diff/2` to support such a case.
> improvement: add `Igniter.Test.diff/2`

- README.md
- documentation/writing-generators.md
- lib/igniter.ex
- lib/igniter/code/common.ex
- lib/igniter/upgrades/igniter.ex
- lib/mix/task.ex
- lib/mix/task/args.ex
- lib/mix/task/info.ex
- lib/mix/tasks/igniter.add_extension.ex
- lib/mix/tasks/igniter.gen.task.ex
- lib/mix/tasks/igniter.move_files.ex
- lib/mix/tasks/igniter.refactor.rename_function.ex
- lib/mix/tasks/igniter.refactor.unless_to_if_not.ex
- lib/mix/tasks/igniter.setup.ex
- lib/mix/tasks/igniter.update_gettext.ex
- lib/mix/tasks/igniter.upgrade.ex
- lib/mix/tasks/igniter.upgrade_igniter.ex
- test/igniter/code/common_test.exs
- test/igniter/mix/task_test.exs
- test/mix/tasks/igniter.gen.task_test.exs
- test/mix/tasks/igniter.upgrade_igniter_test.exs
Work in progress implementation of #126.
> Parse `argv` by default and store in `Igniter` struct (#126)

- mix.exs
The link on https://hex.pm/packages/igniter was going to "https://elixirforum.com/c/elixir-framework-forums/ash-framework-forum" which is a broken link
> Fix elixir forum link

- lib/igniter.ex
- lib/igniter/project/module.ex
- lib/igniter/refactors/rename.ex
- test/igniter/project/formatter_test.exs
Closes #143
I'd like to wait for @leandrocp to confirm that this branch works for him before merging 👍
> fix: pass dot_formatter when updating rewrite sources

- lib/igniter.ex
- test/igniter_test.exs
> fix: print a consistent number of blank lines around diffs

- lib/igniter/libs/swoosh.ex
needed for https://github.com/team-alembic/ash_authentication/pull/835
> feat: add swoosh module

- lib/igniter/code/common.ex
- lib/igniter/libs/phoenix.ex
- lib/igniter/project/config.ex
- lib/igniter/refactors/rename.ex
- test/igniter/code/common_test.exs
We ran into an issue when using igniter with [styler](https://hexdocs.pm/styler/0.8.0/readme.html), where the formatting would move the `@behaviour` tag above the aliases, and then would be incorrectly aliased. I found that using the `expand_env?` argument fixes this, and propagated the option up to `add_code/3`. 
I made an opinionated change here to convert it to an `opts` list, which creates a breaking change for its usage, happy to change if this is too breaking!
Also happy to close this in order to discuss if this doesn't fit the project goals.
> feat: propagate expand_env? option to Igniter.Code.Common.add_code/3

- lib/igniter/project/application.ex
- test/igniter/project/application_test.exs
> improvement: add `:force?` option to `Igniter.Project.Application.add_child/3`

- lib/igniter.ex
- test/igniter/code/file_test.exs
Simple Igniter.mkdir for creating an empty folder.
Suggested it might make sense to use MapSet for the mkdirs list, let me know. MapSet is not used elsewhere in codebase, so maybe just stick to a List.
Also let me know if testing needs expansion. First time touching this codebase..
> Igniter.mkdir

- lib/mix/task.ex
Otherwise an overridden `parse_argv/1` has no effect, as pointed out by dialyzer.
Not sure how to test this TBH.
> Fix parse_argv callback should be overridable

- test/igniter/mix/task_test.exs
> test: ensure `parse_argv/1` can be overridden

- lib/igniter.ex
Existing code would expand to paths outside of project.
Don't quite know how this bug made it in - apologies.
Tried to set up testing, but think we should have Rewrite support for mkdir upstream, before good tests can be made.
> fix: Igniter.mkdir not expanding paths correctly

- lib/igniter.ex
Fixes https://github.com/ash-project/igniter/issues/177#issuecomment-2563939958
Is it necessary to regression test this? If so, what would be the best way? I had a problem reproducing the exact same issue in tests but it's easy to reproduce by creating a new project, installing igniter and running `mix igniter.move_files --check`.
> fix: allow --check to pass when no issues found

- lib/mix/tasks/igniter.upgrade.ex
- Prints out the version diff when upgrading a package; similar behaviour to what `mix deps.upgrade` does
Please let me know if a test is wanted for this
> improvement: print version diff when upgrading packages

- installer/lib/capture_server.ex
- installer/lib/mix/tasks/igniter.install.ex
- installer/lib/task.ex
- lib/igniter.ex
- lib/igniter/util/capture_server.ex
- lib/igniter/util/install.ex
- lib/igniter/util/loading.ex
- lib/mix/task/info.ex
- lib/mix/tasks/igniter.install.ex
- lib/mix/tasks/igniter.upgrade.ex
- mix.exs
- test/mix/tasks/igniter.install_test.exs
> improvement: capture and suppress output in installers

- lib/igniter/project/mix_project.ex
- test/igniter/project/mix_project_test.exs
This was an oversight when I originally implemented this: if the given top-level function doesn't exist, `update/4` is supposed to create it. (That behavior is explicitly stated in the docstring, actually.)
> fix: `Igniter.Project.MixProject.update/4` now creates non-existing functions

- lib/igniter/util/io.ex
Close #193
```
❯ mix igniter.install phoenix_test
==> igniter
Generated igniter app
compile ✔
==> my_app
Update: mix.exs
...|
33 33   |  defp deps do
34 34   |    [
35 + |      {:phoenix_test, "~> 0.5"},
35 36   |      {:igniter, "~> 0.5", path: "/Users/leandro/code/github/leandrocp/igniter"},
36 37   |      {:phoenix, "~> 1.7.18"},
...|
These dependencies should be installed before continuing. Modify mix.exs and install? [Y/n]
Update: mix.exs
...|
42 42   |      {:phoenix_live_reload, "~> 1.2", only: :dev},
43 43   |      {:phoenix_live_view, "~> 1.0.0"},
44    - |      {:floki, ">= 0.30.0", only: :test},
44 + |      {:floki, ">= 0.30.0"},
45 45   |      {:phoenix_live_dashboard, "~> 0.8.3"},
46 46   |      {:esbuild, "~> 0.8", runtime: Mix.env() == :dev},
...|
Conflict in `only` option …
```
> Default `yes?` to Y

- test/igniter/code/common_test.exs
Currently comments are being replaced with `nil` and no comment is injected into the result
> Handling comments in Common.replace_code

- lib/igniter/code/common.ex
- lib/igniter/project/config.ex
- test/igniter/code/common_test.exs
- test/igniter/project/config_test.exs
Expose an opt to move to a matching node.
* Add `:after` opt to `Config` functions
- `configure_new/6`
- `configure/6`
- `modify_configuration_code/5`
* Replace `updater` arg with `opts` in `modify_configuration_code/5`
This introduces a breaking change but it seems more appropriate than adding a new arg. I can revert it tho.
---
Notes:
1. I can push more docs and examples, I just wanted to confirm this looks good first.
2. `move_to/2` is recursive already
> Add `:after` opt to `Config` functions

- lib/igniter.ex
- lib/igniter/util/io.ex
> improvement: better UX around large files

- lib/igniter/project/application.ex
- lib/igniter/project/config.ex
- test/igniter/project/config_test.exs
Resolve config path from project mix.exs file, which unblocks patching config files from within Umbrella child apps.
> fix: resolve project :config_path

- lib/igniter/code/common.ex
- test/igniter/code/common_test.exs
Fixes a typo in the existing docs and switches to doctests to ensure that the docs do not get out of date.
But I am not quite 100% convinced that this is necessarily more readable, it feels a bit awkward to me. I wish I could write a better assertion as the last line of the doctest, we could use a heredoc but then we'd have to annoyingly deal with the trailing newline.
Here's the new and old docs:
| Old       | New     |
| ---------- | ------ |
| ![Screenshot 2025-03-08 14-17-05@2x](https://github.com/user-attachments/assets/5c6ac5f8-dae1-4a29-9263-bc471291f8b3) | ![Screenshot 2025-03-08 14-17-27@2x](https://github.com/user-attachments/assets/0d6ae083-ec4d-47e5-adcd-68807cabb46c) |
> Switch to doctest for Igniter.Code.Common.add_code/3

- lib/igniter/libs/phoenix.ex
- test/igniter/libs/phoenix_test.exs
Hey @zachdaniel here's a PoC to allow customization of routes placement. To fix that conflict between `beacon_site "/"` and Ash Admin in the ash-hq.org generator and also to fix https://github.com/BeaconCMS/beacon/issues/744
I'm not sure about the names in the `:placement` option (Idk if there's a pattern) but `:before_first_scope` is the current behavior that tries to place the route before the first scope, or after the last pipeline, or after use Router. The new option `: bottom_of_module` (not a great name) just place the code at the end of the file.
Here's how the patched file looks like:
```elixir
defmodule TestWeb.Router do
use TestWeb, :router
use Beacon.Router
pipeline :beacon do
plug Beacon.Plug
end
pipeline :browser do
plug(:accepts, ["html"])
plug(:fetch_session) …
```
> Add `:placement` option to `Phoenix.add_scope/4` and `Phoenix.append_to_scope/4`

- CHANGELOG.md
- RELEASE.md
- documentation/upgrades.md
- lib/igniter.ex
- lib/mix/task/info.ex
- lib/mix/tasks/igniter.move_files.ex
- lib/mix/tasks/igniter.phx.install.ex
- lib/mix/tasks/igniter.refactor.unless_to_if_not.ex
- test/igniter/mix/task_test.exs
- test/igniter/project/application_test.exs
- test/igniter/project/igniter_config_test.exs
- test/igniter/project/test_test.exs
Found via `codespell -S deps -L filetest,reenable` and `typos --hidden --format brief`
> docs: fix typos

- lib/mix/tasks/igniter.upgrade.ex
> fix: igniter.upgrade crash on dependency when only option is an atom

- lib/igniter/code/function.ex
- test/igniter/code/function_test.exs
I noticed when trying to use `Function.move_to_def` that I was getting an `:error` when the function hard a guard clause. This should fix that issue as well as test for it.
Definitely let me know if this isn't idiomatic to the way you want the code in Igniter. Happy to work with whatever.
Cheers,
Dan
> Matches function guards when using move_to_def

- installer/lib/mix/tasks/igniter.init.ex
- installer/lib/mix/tasks/igniter.init_library.ex
It adds itself as an optional dependency with `runtime: false`
It then uses Igniter to generate an install task.
> Add igniter.init task to igniter_new archive

- lib/igniter/test.ex
Close #297 
Modifies how `condition` is set in the beginning of the body of `Igniter.Test.assert_has_issue/3` to follow the same pattern as in `Igniter.Test.assert_has_warning/2` and `Igniter.Test.assert_has_notice/2`. The `found_issue` variable was being called before it was created.
All tests that were passing prior to this change still pass, but I didn't see any tests setup to test the macros in `Igniter.Test`.
> Fix: undefined `found_issue` in `Igniter.Test.assert_has_issue/3` #297

- lib/igniter.ex
- lib/igniter/project/config.ex
- test/igniter/project/config_test.exs
Leave anything that you believe does not apply unchecked.
Handles parts of #67
> Implement removal of configuration

- installer/lib/mix/tasks/igniter.new.ex
- installer/test/mix/tasks/igniter.new_test.exs
Skip running `git init` if the project is created inside a `git repo`. If the `IGNITER_SKIP_GIT_CHECK` environment variable is set to `"true"` the check is not performed, and `git init` will run unless the `--no-git` option is passed.
Resolves #327.
Leave anything that you believe does not apply unchecked.
> `igniter.new`: Don't run git init if already in git repo
